version: "3.9"
services:
  neo4j:
    image: neo4j:latest
    restart: always
    env_file:
      - ".env"
    ports:
      - "7474:7474" # UI
      - "7687:7687"
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/import:/import
      - ./neo4j/plugins:/plugins
